### ISSUE TITLE
Item click with a button inside the view

### ISSUE THREAD

**Issue by EmmanueleVilla** [Cheesebaron/Cheesebaron.HorizontalListView#13]
Hi,
my item xml in the horizontal list looks like this:
```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
 android:layout_width="200dp"
    android:layout_height="200dp"
    android:descendantFocusability="blocksDescendants" >
    <ImageView
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
    <ImageButton
        android:id="@+id/imageButton"
        android:layout_width="50dp"
        android:layout_height="50dp"  />
</RelativeLayout>
```
Then I have registered the horizontal  ItemClick and the ImageButton Click events.

Actual behaviour: If I click on the ImageButton, both events are triggered.

Expected behaviour (and actual behaviour on standard components like a gridview): If I click on the ImageButton only its event is triggered

Is this a bug or am I missing something? Can you reproduce this on your side?

Thanks in advance!

**Comment by Cheesebaron** [comment]
Read the nice notice in the readme:

> NOTE: **No longer actively maintained.** I do take pull requests. Consider thinking about whether ViewPager solves your problem instead of using this library.

Basically... don't use this unless you really, really have to!
