### ISSUE TITLE
Cirrious.Mvvmcross is deprecated, It is no more available with nu get

### ISSUE THREAD

**Issue by AmolHegana** [Cheesebaron/Cheesebaron.HorizontalListView#14]
I am not able to build project, Build is getting failed because it is asking for reference of Cirrious.Mvvmcross. Can you please tell, is their any way to build this solution and make it work

**Comment by Cheesebaron** [comment]
MvvmCross 4.x series has changed namespaces. So if you have updated packages, you need to change namespaces too.
